services:
  backend:
    build: .
    container_name: django-blog
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core/:/app/
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: ${MY_SECRET_KEY}
      DEBUG: ${MY_DEBUG}
    env_file:
      - .env
